src/spaceone/inventory/info/common_info.py
test/api/test_cloud_service.py
test/api/test_server.py

Add total_count to StatisticsQuery result

---

src/spaceone/inventory/manager/cleanup_manager.py
src/spaceone/inventory/scheduler/cleanup_scheduler.py
src/spaceone/inventory/service/cleanup_service.py

If resources were disconnected in 48 hours, the resources will be
deleted.

Support Garbage collection on inventory

---

src/spaceone/inventory/manager/collector_manager/__init__.py

Bug fix: collector statistics query error

---

src/spaceone/inventory/info/cloud_service_info.py
src/spaceone/inventory/info/server_info.py
src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/server_model.py

Change server and cloud_service minimal fields

---

src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/collector_service.py
src/spaceone/inventory/service/ip_address_service.py
src/spaceone/inventory/service/job_service.py
src/spaceone/inventory/service/pool_service.py
src/spaceone/inventory/service/server_service.py
src/spaceone/inventory/service/zone_service.py

archiving domain secret when domain is deleted

---

src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/server_service.py

Bug fix: Remove deleted servers when querying statistics

---

src/spaceone/inventory/info/server_info.py
src/spaceone/inventory/model/server_model.py
src/spaceone/inventory/service/server_service.py
test/api/test_server.py

Bug fix: Server's nics format error

---

src/spaceone/inventory/manager/cloud_service_manager.py
src/spaceone/inventory/manager/server_manager.py
src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/server_service.py

Bug fix: move exclude delete resource logic to manager

---

src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/server_service.py

Change keyword search of server and cloud_service

---

src/spaceone/inventory/api/v1/collector.py
src/spaceone/inventory/connector/collector_connector.py
src/spaceone/inventory/error/collector.py
src/spaceone/inventory/info/collector_info.py
src/spaceone/inventory/manager/collector_manager/__init__.py
src/spaceone/inventory/manager/collector_manager/plugin_manager.py
src/spaceone/inventory/model/collector_model.py
src/spaceone/inventory/service/collector_service.py

- New API: init
User can create collector without secret

Support new collector

---

src/spaceone/inventory/manager/collection_data_manager.py

Add a debug code

---

src/spaceone/inventory/manager/collection_data_manager.py
src/spaceone/inventory/service/server_service.py

Change debug code

---

pkg/pip_requirements.txt
src/setup.py
src/spaceone/inventory/manager/collection_data_manager.py
test/api/test_server.py

Remove diff process with jsondiff

---

src/spaceone/inventory/manager/collection_data_manager.py

Bugfix: jsondiff module error

---

src/spaceone/inventory/api/v1/job_task.py
src/spaceone/inventory/api/v1/task_item.py
src/spaceone/inventory/conf/proto_conf.py
src/spaceone/inventory/error/collector.py
src/spaceone/inventory/info/__init__.py
src/spaceone/inventory/info/job_info.py
src/spaceone/inventory/info/job_task_info.py
src/spaceone/inventory/info/task_item_info.py
src/spaceone/inventory/lib/resource_manager.py
src/spaceone/inventory/manager/collector_manager/__init__.py
src/spaceone/inventory/manager/collector_manager/collecting_manager.py
src/spaceone/inventory/manager/collector_manager/filter_manager.py
src/spaceone/inventory/manager/collector_manager/job_manager.py
src/spaceone/inventory/manager/collector_manager/job_task_manager.py
src/spaceone/inventory/manager/collector_manager/task_item_manager.py
src/spaceone/inventory/model/__init__.py
src/spaceone/inventory/model/job_model.py
src/spaceone/inventory/model/job_task_model.py
src/spaceone/inventory/model/task_item_model.py
src/spaceone/inventory/service/__init__.py
src/spaceone/inventory/service/job_task_service.py
src/spaceone/inventory/service/task_item_service.py

Support Job, JobTask, TaskItem API

---

src/spaceone/inventory/scheduler/cleanup_scheduler.py
src/spaceone/inventory/scheduler/inventory_scheduler.py

Update consul wait

---

src/spaceone/inventory/manager/collection_data_manager.py

Bug fix: data merge issue

---

src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/server_service.py

Change project mapping rule

---

src/spaceone/inventory/model/collector_model.py

Optimize collector model meta spec

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/region_model.py
src/spaceone/inventory/model/server_model.py

Change db index

---

src/spaceone/inventory/info/job_info.py
src/spaceone/inventory/info/job_task_info.py
src/spaceone/inventory/manager/collector_manager/__init__.py
src/spaceone/inventory/manager/collector_manager/collecting_manager.py
src/spaceone/inventory/manager/collector_manager/job_manager.py
src/spaceone/inventory/manager/collector_manager/job_task_manager.py
src/spaceone/inventory/model/job_model.py
src/spaceone/inventory/model/job_task_model.py
src/spaceone/inventory/service/cleanup_service.py

- change field state -> status

Update Job JobTask API

---

src/spaceone/inventory/manager/collector_manager/__init__.py
src/spaceone/inventory/manager/collector_manager/job_manager.py
src/spaceone/inventory/manager/collector_manager/job_task_manager.py
src/spaceone/inventory/model/job_model.py

Fix Job Status

---

src/spaceone/inventory/service/cloud_service_service.py

Change a cloud service query spec

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py
src/spaceone/inventory/manager/collector_manager/job_task_manager.py
src/spaceone/inventory/model/job_task_model.py
src/spaceone/inventory/scheduler/inventory_db_updater.py

collector can update DB asynchoronously

Add new feature

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py
src/spaceone/inventory/scheduler/inventory_db_updater.py

Fix RESPONSE type

---

src/spaceone/inventory/manager/collector_manager/__init__.py
src/spaceone/inventory/manager/collector_manager/job_task_manager.py

Add secret, project information when job_task is created

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py

Support asynchronus DB update

---

src/spaceone/inventory/lib/resource_manager.py

Preserve updated_at when disconnected or deleted

---

src/spaceone/inventory/model/collector_model.py

Update interval schedule to 3600 sec

---

src/spaceone/inventory/manager/collection_data_manager.py
test/api/test_server.py

add merge mode when updating server and cloud service

---

src/spaceone/inventory/manager/collection_data_manager.py

Temporary code before metadata migration

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py

add plugin_id in transaction.meta

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/server_model.py

Bug fix: syntax error (region)

Bug fix: add a deleted_at to cloud service's updatable_fields

---

src/spaceone/inventory/manager/cloud_service_manager.py

Bug fix: deleted cloud service query issue

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py

Support update_mode

---

src/spaceone/inventory/model/collector_model.py
src/spaceone/inventory/scheduler/__init__.py
src/spaceone/inventory/scheduler/interval_scheduler.py
src/spaceone/inventory/service/collector_service.py

Support interval scheduler

---

pkg/pip_requirements.txt

Update pip requirements

---

Dockerfile
pkg/pip_requirements.txt
src/setup.py

Change a Dockerfile

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/job_model.py

Change lookup field settings

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/cloud_service_type_model.py
src/spaceone/inventory/model/job_model.py
src/spaceone/inventory/model/region_model.py
src/spaceone/inventory/model/server_model.py
src/spaceone/inventory/service/region_service.py
test/api/test_cloud_service.py

Remove aggregate lookup conf in model

Add a reference fields (ref_region, ref_cloud_service_type)

---

src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/server_service.py

Bug fix: server and cloud service search memory issue

---

src/spaceone/inventory/info/resource_group_info.py
src/spaceone/inventory/manager/resource_group_manager.py
src/spaceone/inventory/model/resource_group_model.py
src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/server_service.py
test/api/test_resource_group.py

Add a keyword filter to resource group settings

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/server_model.py

cleanup takes huge memory for sorting
Remove ordering in Server and CloudService

Remove ordering in Server and CloudService

---

src/spaceone/inventory/manager/collection_data_manager.py

Add debug code

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/server_model.py

Add power_state data to server and cloud service model

---

src/spaceone/inventory/manager/collection_data_manager.py

bug fix: merge mode issue

---

src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/server_service.py

bug fix: region type or region code null issue

---

src/spaceone/inventory/connector/__init__.py
src/spaceone/inventory/connector/config_connector.py
src/spaceone/inventory/manager/__init__.py
src/spaceone/inventory/manager/cleanup_manager.py
src/spaceone/inventory/manager/config_manager.py
src/spaceone/inventory/service/cleanup_service.py

Add garbage_collection policy from config service

---

src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/cloud_service_type_service.py
src/spaceone/inventory/service/region_service.py
src/spaceone/inventory/service/server_service.py

Bug fix: region and cloud service type reference issue

---

src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/cloud_service_type_service.py
src/spaceone/inventory/service/collector_service.py
src/spaceone/inventory/service/job_service.py
src/spaceone/inventory/service/job_task_service.py
src/spaceone/inventory/service/region_service.py
src/spaceone/inventory/service/resource_group_service.py
src/spaceone/inventory/service/server_service.py

Add keyword filter to stat api

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/cloud_service_type_model.py
src/spaceone/inventory/model/server_model.py

Add indexes (collector, service_account, secret)

---

src/spaceone/inventory/model/job_model.py
src/spaceone/inventory/model/job_task_model.py
src/spaceone/inventory/service/cloud_service_service.py

Add job and job task indexes 

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/cloud_service_type_model.py
src/spaceone/inventory/model/region_model.py
src/spaceone/inventory/model/server_model.py
test/api/test_region.py

change updatable fields

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/cloud_service_type_model.py
src/spaceone/inventory/model/server_model.py

add date indexes

---

src/spaceone/inventory/lib/resource_manager.py
src/spaceone/inventory/manager/cleanup_manager.py
src/spaceone/inventory/model/collection_info_model.py

Bug fix: updated_at is changed to null issue

---

src/spaceone/inventory/info/cloud_service_info.py
src/spaceone/inventory/info/cloud_service_type_info.py
src/spaceone/inventory/info/collector_info.py
src/spaceone/inventory/info/region_info.py
src/spaceone/inventory/info/resource_group_info.py
src/spaceone/inventory/info/server_info.py
src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/cloud_service_type_model.py
src/spaceone/inventory/model/collector_model.py
src/spaceone/inventory/model/region_model.py
src/spaceone/inventory/model/resource_group_model.py
src/spaceone/inventory/model/server_model.py
src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/cloud_service_type_service.py
src/spaceone/inventory/service/collector_service.py
src/spaceone/inventory/service/region_service.py
src/spaceone/inventory/service/resource_group_service.py
src/spaceone/inventory/service/server_service.py
test/api/test_cloud_service.py
test/api/test_cloud_service_type.py
test/api/test_region.py
test/api/test_resource_group.py
test/api/test_server.py

Change tag field format

---

src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/cloud_service_type_service.py
src/spaceone/inventory/service/region_service.py
src/spaceone/inventory/service/server_service.py

Add temp code for tag migration

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/cloud_service_type_model.py
src/spaceone/inventory/model/region_model.py
src/spaceone/inventory/model/server_model.py

Change default ordering

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/cloud_service_type_model.py
src/spaceone/inventory/model/region_model.py
src/spaceone/inventory/model/server_model.py

Remove tags indexes

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/cloud_service_type_model.py
src/spaceone/inventory/model/region_model.py
src/spaceone/inventory/model/server_model.py

Disable auto create index settings

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/cloud_service_type_model.py
src/spaceone/inventory/model/server_model.py

Change compound index name

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py

Remove debug message

---

src/spaceone/inventory/manager/collector_manager/__init__.py

Finish job if there is no task to do

---

docs/feature_garbage_collection.md
release_notes/version_1.6.1.md
src/spaceone/inventory/info/job_task_info.py
src/spaceone/inventory/lib/resource_manager.py
src/spaceone/inventory/manager/cleanup_manager.py
src/spaceone/inventory/manager/collection_data_manager.py
src/spaceone/inventory/manager/collector_manager/collecting_manager.py
src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/cloud_service_type_model.py
src/spaceone/inventory/model/collection_info_model.py
src/spaceone/inventory/model/job_task_model.py
src/spaceone/inventory/model/server_model.py
src/spaceone/inventory/service/cleanup_service.py
src/spaceone/inventory/service/server_service.py

See docs/feature_garbage_collection.md

New feature - garbage collection after collecting data

---

src/spaceone/inventory/conf/global_conf.py
src/spaceone/inventory/info/cloud_service_info.py
src/spaceone/inventory/info/collector_info.py
src/spaceone/inventory/info/server_info.py
src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/cloud_service_type_model.py
src/spaceone/inventory/model/collector_model.py
src/spaceone/inventory/model/job_model.py
src/spaceone/inventory/model/job_task_model.py
src/spaceone/inventory/model/region_model.py
src/spaceone/inventory/model/resource_group_model.py
src/spaceone/inventory/model/server_model.py

Apply index and unique check db features

---

src/spaceone/inventory/model/collector_model.py

Change database options

---

src/spaceone/inventory/manager/collector_manager/__init__.py
src/spaceone/inventory/manager/collector_manager/collecting_manager.py
src/spaceone/inventory/service/collector_service.py

Support update metadata

---

src/spaceone/inventory/service/job_service.py
src/spaceone/inventory/service/job_task_service.py

Fix Job and JobTask status filter

---

src/spaceone/inventory/model/collector_model.py
src/spaceone/inventory/model/job_model.py

Add db indexes

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/job_model.py
src/spaceone/inventory/model/job_task_model.py
src/spaceone/inventory/model/resource_group_model.py
src/spaceone/inventory/model/server_model.py
src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/cloud_service_type_service.py
src/spaceone/inventory/service/collector_service.py
src/spaceone/inventory/service/job_service.py
src/spaceone/inventory/service/job_task_service.py
src/spaceone/inventory/service/region_service.py
src/spaceone/inventory/service/resource_group_service.py
src/spaceone/inventory/service/server_service.py

Add RBAC features

---

src/spaceone/inventory/conf/global_conf.py

Change default config

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py
src/spaceone/inventory/scheduler/cleanup_scheduler.py
src/spaceone/inventory/scheduler/interval_scheduler.py
src/spaceone/inventory/scheduler/inventory_scheduler.py
src/spaceone/inventory/service/cleanup_service.py

add metadata
- service
- resource
- verb

Fix scheduler for RBAC

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py

Add mutation in transaction

---

src/spaceone/inventory/manager/collection_data_manager.py

Add debug codes

---

src/spaceone/inventory/manager/collection_data_manager.py

Fix a data merge mode bug

---

src/spaceone/inventory/manager/collection_data_manager.py

Fix a merge bug

---

src/spaceone/inventory/manager/collector_manager/__init__.py
src/spaceone/inventory/manager/collector_manager/collecting_manager.py

Fix garbage collection

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py

Add inventory.ErrorResource

---

src/spaceone/inventory/manager/collector_manager/__init__.py
src/spaceone/inventory/model/job_model.py
src/spaceone/inventory/service/collector_service.py

Remove application-level cascade delete logic

---

src/spaceone/inventory/service/collector_service.py

Fix a tag update bug

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/server_model.py

Change cloud service and server index

---

src/spaceone/inventory/conf/global_conf.py

Change local cache ttl

---

src/spaceone/inventory/connector/collector_connector.py
src/spaceone/inventory/manager/collector_manager/collecting_manager.py

Change max message length when collecting resources

---

src/spaceone/inventory/connector/plugin_connector.py
src/spaceone/inventory/info/collector_info.py
src/spaceone/inventory/manager/collector_manager/__init__.py
src/spaceone/inventory/manager/collector_manager/collecting_manager.py
src/spaceone/inventory/manager/collector_manager/plugin_manager.py
src/spaceone/inventory/model/collector_model.py
src/spaceone/inventory/service/collector_service.py

feat: add auto plugin upgrade feature

---

src/spaceone/inventory/manager/collector_manager/__init__.py
src/spaceone/inventory/service/collector_service.py

fix: fix update plugin bug

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py

test: add debug code

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py

test: remove debug code

---

src/spaceone/inventory/conf/global_conf.py

refactor: remove unused configuration

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py

fix: fix initialization bug

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py

fix: fix debug code

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py

fix: fix collecting bug

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/server_model.py

feat: add field to cloud service and server model

---

src/spaceone/inventory/api/v1/cloud_service_type.py
src/spaceone/inventory/error/server.py
src/spaceone/inventory/info/cloud_service_info.py
src/spaceone/inventory/info/cloud_service_type_info.py
src/spaceone/inventory/info/collection_info.py
src/spaceone/inventory/info/region_info.py
src/spaceone/inventory/info/server_info.py
src/spaceone/inventory/manager/collector_manager/job_task_manager.py
src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/cloud_service_type_model.py
src/spaceone/inventory/model/collection_info_model.py
src/spaceone/inventory/model/collection_state_model.py
src/spaceone/inventory/model/collector_model.py
src/spaceone/inventory/model/job_model.py
src/spaceone/inventory/model/job_task_model.py
src/spaceone/inventory/model/region_model.py
src/spaceone/inventory/model/server_model.py
src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/cloud_service_type_service.py
src/spaceone/inventory/service/collector_service.py
src/spaceone/inventory/service/region_service.py
src/spaceone/inventory/service/server_service.py

feat: change resource's fields

---

src/spaceone/inventory/info/cloud_service_info.py
src/spaceone/inventory/info/server_info.py
src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/server_model.py

feat: change field type

---

src/spaceone/inventory/manager/cleanup_manager.py
src/spaceone/inventory/manager/collection_state_manager.py
src/spaceone/inventory/manager/collector_manager/collecting_manager.py
src/spaceone/inventory/model/collection_state_model.py

fix: fix a garbage collection bug

---

src/spaceone/inventory/manager/collector_manager/__init__.py
src/spaceone/inventory/manager/collector_manager/collecting_manager.py
src/spaceone/inventory/manager/collector_manager/job_manager.py
src/spaceone/inventory/manager/collector_manager/job_task_manager.py

refactor: change task error message

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py

fix: fix typo

---

src/spaceone/inventory/manager/collector_manager/job_task_manager.py

refactor: change job task failure state condition

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py
src/spaceone/inventory/manager/collector_manager/job_manager.py
src/spaceone/inventory/manager/collector_manager/job_task_manager.py
src/spaceone/inventory/model/job_task_model.py

refactor: apply cancellation of same job task

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py
src/spaceone/inventory/manager/collector_manager/job_task_manager.py

fix: fix a job status bug

---

src/spaceone/inventory/model/job_task_model.py

fix: change job task model

---

src/spaceone/inventory/manager/collector_manager/collecting_manager.py
src/spaceone/inventory/scheduler/interval_scheduler.py
src/spaceone/inventory/scheduler/inventory_scheduler.py

refactor: change logging policy

---

src/spaceone/inventory/manager/collector_manager/job_task_manager.py

refactor: change duplicate job task condition

---

src/spaceone/inventory/manager/collector_manager/job_task_manager.py

fix: fix argument bug

---

src/spaceone/inventory/manager/collector_manager/job_task_manager.py

refactor: add debug code

---

src/spaceone/inventory/manager/collector_manager/job_task_manager.py

fix: fix duplicate job query

---

src/spaceone/inventory/info/cloud_service_info.py
src/spaceone/inventory/info/server_info.py
src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/server_model.py
src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/server_service.py

fix: change field name

---

src/spaceone/inventory/manager/collector_manager/job_manager.py

refactor: change job timeout policy

---

src/spaceone/inventory/manager/collection_data_manager.py

fix: fix change history type error

---

src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/cloud_service_type_service.py
src/spaceone/inventory/service/server_service.py

refactor: change keyword filters for search

---

src/spaceone/inventory/scheduler/cleanup_scheduler.py
src/spaceone/inventory/scheduler/interval_scheduler.py
src/spaceone/inventory/scheduler/inventory_scheduler.py

fix: fix time bug

---

src/spaceone/inventory/manager/collector_manager/__init__.py
src/spaceone/inventory/manager/collector_manager/job_manager.py
src/spaceone/inventory/model/job_model.py

refactor: apply project permission to job resource

---

src/spaceone/inventory/manager/collector_manager/__init__.py

refactor: optimize projects data in job model

---

src/spaceone/inventory/manager/identity_manager.py
src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/server_service.py

feat: add project_group_id filter to server and cloud service

---

src/spaceone/inventory/info/collector_info.py

fix: fix bug in Collector.list_schedules API

---

src/spaceone/inventory/manager/collector_manager/__init__.py

fix: fix bug when enable collector

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/service/cloud_service_service.py

feat: add ip_address for cloud service query
[AWS EC2] Migrate Server Resources to Cloud Service Resources ([#72](https://github.com/spaceone-dev/plugin-aws-ec2-inven-collector/issues/72))

feat: add ip_adress for cloud service query

---

src/spaceone/inventory/service/cloud_service_service.py

add ip_addresses to keyword filter for cloud service search

feat: add ip_addresses to keyword filter for cloud service search

---

src/spaceone/inventory/scheduler/cleanup_scheduler.py

fix: fix scheduler metadata bug

---

src/spaceone/inventory/info/change_history_info.py
src/spaceone/inventory/manager/change_history_manager.py
src/spaceone/inventory/model/record_model.py
src/spaceone/inventory/service/change_history_service.py
src/spaceone/inventory/service/note_service.py

Refactor Change History Search

---

src/spaceone/inventory/model/record_model.py

fix: change diff field type

---

src/spaceone/inventory/info/change_history_info.py
src/spaceone/inventory/manager/change_history_manager.py
src/spaceone/inventory/model/record_model.py

reat: add diff_count field

---

src/spaceone/inventory/model/cloud_service_model.py

reat: add deleted_at index in cloud_service

---

src/spaceone/inventory/service/change_history_service.py

refactor: change required fields

---

src/spaceone/inventory/model/cloud_service_model.py

refactor: remove default sorting option of cloud service model

---

src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/service/cloud_service_service.py

fix: fix wrong metadata path

---

src/spaceone/inventory/manager/change_history_manager.py
src/spaceone/inventory/manager/note_manager.py
src/spaceone/inventory/model/note_model.py
src/spaceone/inventory/model/record_model.py
src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/note_service.py

Refactor Change History

---

src/spaceone/inventory/service/cloud_service_service.py

fix: fix ip_addresses null issue

---

src/spaceone/inventory/model/record_model.py

refactor: add index

---

src/spaceone/inventory/service/cleanup_service.py

feat: cascade delete record and note when terminating cloud services

---

src/spaceone/inventory/info/cloud_service_info.py
src/spaceone/inventory/info/cloud_service_type_info.py
src/spaceone/inventory/info/collector_info.py
src/spaceone/inventory/info/region_info.py
src/spaceone/inventory/info/resource_group_info.py
src/spaceone/inventory/info/server_info.py
src/spaceone/inventory/model/cloud_service_model.py
src/spaceone/inventory/model/cloud_service_type_model.py
src/spaceone/inventory/model/collector_model.py
src/spaceone/inventory/model/region_model.py
src/spaceone/inventory/model/resource_group_model.py
src/spaceone/inventory/model/server_model.py
src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/cloud_service_type_service.py
src/spaceone/inventory/service/collector_service.py
src/spaceone/inventory/service/region_service.py
src/spaceone/inventory/service/resource_group_service.py
src/spaceone/inventory/service/server_service.py

refactor: change tag type from list of dict to dict in resources

---

src/spaceone/inventory/service/change_history_service.py
src/spaceone/inventory/service/cloud_service_service.py
src/spaceone/inventory/service/job_service.py
src/spaceone/inventory/service/job_task_service.py
src/spaceone/inventory/service/note_service.py
src/spaceone/inventory/service/resource_group_service.py

refactor: change authorization scope
